export { default as Combo } from './combo/Combo.jsx'
export { default as Burger } from './burger/Burger.jsx'
export { default as Snacks } from './snacks/Snacks.jsx'
export { default as Drinks } from './drinks/Drinks.jsx'
export { default as Hot_Drinks } from './hot_drinks/Hot_Drinks.jsx'
export { default as Sause } from './sause/Sause.jsx'
export { default as Footer } from './footer/Foolter.jsx'
export { default as Navbar } from './navbar/Navbar';
export { default as Header } from './header/Header';
export { default as Hero } from './hero/Hero';